spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: false
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/budget
    username: budget_user
    password: password
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${BPS_CLIENT_ID}
            client-secret: ${BPS_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://budget-planner.us.auth0.com/
      resource-server:
        jwt:
          issuer-uri: https://budget-planner.us.auth0.com/
auth0:
  audience: https://api.budget-planner
  domain: https://budget-planner.us.auth0.com
debug: false
logging:
  level:
    root: INFO
budget-planner:
  static:
    path: ${BPS_STATIC_PATH:/var/www/budget-planner}